# Jekyll configuration

name: boxes
description: Command line ASCII boxes unlimited!

# enable emoticons
gems: ["emoji_for_jekyll"]

# url is currently only used only for the RSS feed in feed.xml
url: http://ascii-boxes.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: /boxes

# This can be '' to hide the Github nav button
github: 'ascii-boxes/boxes'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-23698164-1'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

permalink: /:year/:month/:title
paginate: 10

highlighter: rouge
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
markdown: kramdown
kramdown:
  input: GFM

exclude: ['README.md', 'LICENSE']

# boxes custom variables
defaults:
  -
    scope:
      path: ""   # everywhere
    values:
      bxemail: '&lt;boxes(at)thomasjensen.com&gt;'
